/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-bright':               '#fef8f1',
        'surface':                      '#fef8f1',
        'on-primary-container':         '#795e44',
        'secondary-fixed':              '#bbebf1',
        'secondary-container':          '#b8e8ee',
        'on-tertiary-container':        '#007422',
        'surface-container-low':        '#f9f3ec',
        'on-surface':                   '#1d1b17',
        'surface-variant':              '#e7e2db',
        'outline':                      '#80756c',
        'surface-container-highest':    '#e7e2db',
        'error':                        '#ba1a1a',
        'error-container':              '#ffdad6',
        'on-error-container':           '#93000a',
        'tertiary-fixed':               '#93f993',
        'inverse-on-surface':           '#f6f0e9',
        'background':                   '#fef8f1',
        'on-error':                     '#ffffff',
        'tertiary':                     '#006e20',
        'on-tertiary':                  '#ffffff',
        'inverse-primary':              '#e3c0a0',
        'outline-variant':              '#d2c4b9',
        'surface-dim':                  '#dfd9d2',
        'on-secondary-container':       '#3b6a6f',
        'surface-container-lowest':     '#ffffff',
        'primary-container':            '#ffdab9',
        'on-background':                '#1d1b17',
        'on-primary-fixed-variant':     '#5a422a',
        'on-surface-variant':           '#4f453d',
        'on-primary':                   '#ffffff',
        'primary-fixed':                '#ffdcbe',
        'inverse-surface':              '#32302c',
        'secondary-fixed-dim':          '#9fcfd5',
        'primary-fixed-dim':            '#e3c0a0',
        'primary':                      '#74593f',
        'tertiary-fixed-dim':           '#77dc7a',
        'surface-tint':                 '#74593f',
        'tertiary-container':           '#91f892',
        'surface-container-high':       '#ede7e0',
        'on-primary-fixed':             '#2a1704',
        'on-secondary':                 '#ffffff',
        'on-secondary-fixed-variant':   '#1d4d53',
        'secondary':                    '#37656b',
        'surface-container':            '#f3ede6',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm:     '0.5rem',
        lg:     '2rem',
        xl:     '3rem',
        full:   '9999px',
      },
      spacing: {
        lg:                 '24px',
        md:                 '16px',
        xs:                 '4px',
        sm:                 '8px',
        xl:                 '32px',
        'container-margin': '20px',
      },
      fontFamily: {
        sans:       ['Quicksand', 'system-ui', 'sans-serif'],
        'body-md':  ['Quicksand'],
        'label-sm': ['Quicksand'],
        'headline-md': ['Quicksand'],
        'headline-sm': ['Quicksand'],
        'caption':  ['Quicksand'],
        'body-lg':  ['Quicksand'],
        'display-lg': ['Quicksand'],
      },
      fontSize: {
        'body-md':    ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-sm':   ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md':['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm':['20px', { lineHeight: '28px', fontWeight: '600' }],
        'caption':    ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg':    ['18px', { lineHeight: '26px', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'soft':     '0 8px 20px rgba(116,89,63,0.06)',
        'soft-lg':  '0 4px 12px rgba(116,89,63,0.12)',
        'nav':      '0 -4px 20px rgba(116,89,63,0.06)',
        'fab':      '0 8px 24px rgba(255,218,185,0.6)',
      }
    },
  },
  plugins: [],
}
